# Generated by Django 4.0.2 on 2022-02-21 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_description_alter_category_category_name'),
        ('product', '0006_product_description_alter_category_category_name_and_more'),
        ('product', '0008_product_description_alter_category_category_name_and_more'),
    ]

    operations = [
    ]
